version: '3.1'

services:
  redis:
    container_name: poc-bullproject-redis
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

networks:
  default:
