# @name HealthCheck

# @description
# This is a health check for the application. It will return a 200 status code
# if the application is running correctly.

GET http://localhost:3000/

### 

# @name CreateNewJob

# @description
# This endpoint will create a new job in the database.

POST http://localhost:3000/add-job
Content-Type: application/json

{
  "name": "Job Name"
}
